version: '3.4'

services:
  crs:
    image: crs
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 1337:1337
    volumes:
      - .:/usr/src/app
    links:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: